#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/EG_160614_Cellular_Automata_Designtool.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/peasycam.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/dxf.jar:$APPDIR/lib/OBJExport.jar" EG_160614_Cellular_Automata_Designtool "$@"
